[default.github]
tokens = [
    "1234567890abfc5ea1234567890abcdef1234"
]

[default.github_app]
app_id = 12345
client_id = "1234567890abcdef1234"
client_secret = "1234567890abcdef1234"
private_key = """
-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA2Wc5mC2Ys9...
"""
# or: private_key = "/path/to/private_key.pem"

[default.email]
server = "smtp.gmail.com"
port = 587
username = "12f23ed4f5g6h7j8k9l0"
password = "12f23ed4f5g6h7j8k9l0"
