[gfibot]
projects = [
    "osmlab/name-suggestion-index",
    "scikit-learn/scikit-learn",
    "pandas-dev/pandas",
    "mui-org/material-ui",
]

[mongodb]
url = "mongodb://localhost:27017"
db = "gfibot"

[mongodb.collections.repos]
name = "repos"
index = ["owner", "name"]
unique = true

[mongodb.collections.repos_commits]
name = "repos.commits"
index = ["owner", "name", "sha"]
unique = true

[mongodb.collections.repos_issues]
name = "repos.issues"
index = ["owner", "name", "number"]
unique = true

[mongodb.collections.repos_users]
name = "repos.users"
index = ["owner", "name", "user"]
unique = true

[mongodb.collections.issues]
name = "issues"
index = ["owner", "name", "number"]
unique = true

[mongodb.collections.users]
name = "users"
index = ["name"]
unique = true

[tool.poetry]
name = "gfi-bot"
version = "0.1.0"
description = "ML-powered 🤖 for finding and labeling good first issues in your GitHub project!"
authors = [
    "Hao He <heh@pku.edu.cn>",
    "Wenxin Xiao <wenxin.xiao@stu.pku.edu.cn>",
    "Runzhi He <rzhe@pku.edu.cn>",
]

[tool.poetry.dependencies]
python = "^3.9"
pymongo = { extras = ["srv"], version = "^4.0.1" }
toml = "^0.10.2"
requests = "^2.26.0"
PyGithub = "^1.55"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "*"
pre-commit = "*"
