[gfibot]
projects = []

[mongodb]
url = "mongodb://localhost:27017"
db = "gfibot"

[mongodb.collections.repositories]
name = "repositories"
index = ["name", "owner"]
unique = true

[mongodb.collections.issues]
name = "issues"
index = ["repo_name", "repo_owner", "number"]
unique = true

[mongodb.collections.users]
name = "users"
index = ["name"]
unique = true

[mongodb.collections.users_repo]
name = "users.repo"
index = ["repo_name", "repo_owner", "name"]
unique = true

[tool.poetry]
name = "gfi-bot"
version = "0.1.0"
description = "ML-powered 🤖 for finding and labeling good first issues in your GitHub project!"
authors = [
    "Hao He <heh@pku.edu.cn>",
    "Wenxin Xiao <wenxin.xiao@stu.pku.edu.cn>",
    "Runzhi He <rzhe@pku.edu.cn>",
]

[tool.poetry.dependencies]
python = "^3.9"
pymongo = "^4.0.1"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "*"
pre-commit = "*"
