version: '3'

services:
    
    mongodb:
        image: mongo
        container_name: mongodb
        volumes:
            - /data/heh/mongodb:/data/db
        command: mongod --bind_ip=0.0.0.0 --port=27020
        ports:
            - "27020:27020"
    
    gfi-bot:
        build:
            context: ../
            dockerfile: ./production/gfibot.backend.dockerfile
        ports:
            - "5000:5000" 
        depends_on:
            - mongodb

    gfi-bot-frontend:
        build:
            context: ../
            dockerfile: ./production/gfibot.frontend.dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - gfi-bot 
