version: "2.2"

services:
  mongodb:
    image: mongo
    volumes:
      - ${GFIBOT_DATA_DIR}/mongodb:/data/db
    command: mongod --bind_ip=0.0.0.0 --port=27020
    ports:
      - "${GFIBOT_MONGO_PORT}:27020"
    # mem_limit: 12G
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  gfi-bot:
    build:
      context: ../
      dockerfile: ./production/gfibot.dockerfile
    ports:
      - "${GFIBOT_BACKEND_PORT}:5000"
    depends_on:
      - mongodb
    volumes:
      - ${GFIBOT_DATA_DIR}/models:/models
      - ${GFIBOT_DATA_DIR}/nltk_data:/root/nltk_data
    # mem_limit: 16G
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    build:
      context: ../
      dockerfile: ./production/frontend.dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL:-http://localhost:5000}
    ports:
      - "${GFIBOT_HTTP_PORT}:80"
      - "${GFIBOT_HTTPS_PORT}:443"
    restart: always
    environment:
      - REACT_APP_BASE_URL
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ${GFIBOT_DATA_DIR}/certs/:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/
    depends_on:
      - gfi-bot
