name: GFI-Bot Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4.1
        command: mongod --port 27020
        ports:
          - 27020:27020

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --user poetry
        poetry install
    - name: Set up a GitHub token
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} >> tokens.txt
    - name: Test with pytest
      run: |
        poetry run pytest --cov=./gfibot --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
